// Code generated by goctl. DO NOT EDIT.
// Source: reply.proto

package replyclient

import (
	"context"

	"github.com/liujingkaiai/go-zero-mall/apps/reply/rpc/reply"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentItem      = reply.CommentItem
	CommentsRequest  = reply.CommentsRequest
	CommentsResponse = reply.CommentsResponse

	Reply interface {
		Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.Comments(ctx, in, opts...)
}
