Name: product.rpc
ListenOn: 0.0.0.0:8081
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc


DataSource: product:NZXEFYX3SWKetYEE@tcp(127.0.0.1:3306)/product

CacheRedis: 
  - Host: 127.0.0.1:6379 
    Pass: 
    Type: none